/**
 * Копирует однопоточную lite-сборку Stockfish из node_modules/stockfish
 * в public/engine/ (файлы сохраняют имена — js-скрипт ищет .wasm рядом с собой)
 * и генерирует src/engine/files.gen.ts с фактическими именами файлов.
 */
import { copyFileSync, existsSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const pkgDir = join(root, 'node_modules', 'stockfish');
const outDir = join(root, 'public', 'engine');

if (!existsSync(pkgDir)) {
  console.error('node_modules/stockfish not found — run npm install first');
  process.exit(1);
}

const files = ['bin', 'src', '.']
  .flatMap((dir) => {
    const full = dir === '.' ? pkgDir : join(pkgDir, dir);
    return existsSync(full) ? readdirSync(full).map((f) => (dir === '.' ? f : `${dir}/${f}`)) : [];
  })
  .filter((f) => /\.(js|wasm)$/.test(f));

const findPair = (re) => {
  const js = files.filter((f) => re.test(f) && f.endsWith('.js')).sort();
  const wasm = files.filter((f) => re.test(f) && f.endsWith('.wasm')).sort();
  return js.length && wasm.length
    ? { js: js[js.length - 1].replace(/\\/g, '/'), wasm: wasm[wasm.length - 1].replace(/\\/g, '/') }
    : null;
};

// Приоритет: lite-single (без встоенной большой сети, ~2–5 МБ, без SharedArrayBuffer).
const pair =
  findPair(/lite-single/) ??
  findPair(/-single(-(haskell|nnue-\d+))?\.js$/) ??
  findPair(/nnue-\d+-single/);

if (!pair) {
  console.error('No single-threaded stockfish build found in', pkgDir);
  process.exit(1);
}

mkdirSync(outDir, { recursive: true });
copyFileSync(join(pkgDir, pair.js), join(outDir, pair.js.split('/').pop()));
copyFileSync(join(pkgDir, pair.wasm), join(outDir, pair.wasm.split('/').pop()));

const gen = `// AUTO-GENERATED by scripts/copy-engine.mjs — не редактировать вручную.
export const ENGINE_JS = '${pair.js.split('/').pop()}';
export const ENGINE_WASM = '${pair.wasm.split('/').pop()}';
`;
writeFileSync(join(root, 'src', 'engine', 'files.gen.ts'), gen);
console.log(`Copied ${pair.js} + ${pair.wasm} -> public/engine/`);
